name: SAST (Sonarqube)

# Reusable SAST scan using Sonarqube

on:
  workflow_call:

permissions:
  contents: read

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup variables
        run: |
          PROJECT_KEY="${GITHUB_REPOSITORY##*/}"
          
          PROJECT_NAME=$(echo "$PROJECT_KEY" \
            | tr '_-' ' ' \
            | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')
          
          echo "PROJECT_KEY=$PROJECT_KEY" >> $GITHUB_ENV
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ env.PROJECT_KEY }}
            "-Dsonar.projectName=${{ env.PROJECT_NAME }}"
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
