name: SAST (Sonarqube)

# Reusable SAST scan using Sonarqube

on:
  workflow_call:
    inputs:
      service_key:
        required: true
        type: string
      service_name:
        required: false
        type: string

permissions:
  contents: read

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.service_key }}
            "-Dsonar.projectName=${{ inputs.service_name }}"
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
